import type { Program } from './types'

// BJJ-focused strength program. Hard constraint: lifting happens at lunchtime
// ~6h before evening rolling, so sessions are ~45 min, capped at RPE 7-8, and
// heavy grip work is kept to Day D (furthest from the next BJJ session).
export const SEED_PROGRAM: Program = {
  id: 'bjj-slp-v1',
  name: 'BJJ Strength & Physique',
  days: [
    {
      id: 'day-a-lower',
      name: 'Day A — Lower Strength',
      weekdayHints: [1], // Monday
      exercises: [
        {
          id: 'back-squat',
          name: 'Back Squat',
          targetSets: 4,
          repRangeMin: 4,
          repRangeMax: 6,
          targetRpe: 7,
          restSeconds: 180,
          loadIncrementKg: 5,
          progression: 'double',
          notes: 'Hip drive for shots, bridges and guard retention. Stop at RPE 7 — you roll tonight.',
          substitutions: ['Front Squat', 'Leg Press'],
        },
        {
          id: 'romanian-deadlift',
          name: 'Romanian Deadlift',
          targetSets: 3,
          repRangeMin: 8,
          repRangeMax: 10,
          targetRpe: 7,
          restSeconds: 150,
          loadIncrementKg: 5,
          progression: 'double',
          notes: 'Posterior chain — hamstrings and hips. Controlled eccentric, no grinding.',
          substitutions: ['DB Romanian Deadlift', '45° Back Extension'],
        },
        {
          id: 'bulgarian-split-squat',
          name: 'Bulgarian Split Squat',
          targetSets: 2,
          repRangeMin: 8,
          repRangeMax: 10,
          perSide: true,
          targetRpe: 8,
          restSeconds: 90,
          loadIncrementKg: 2.5,
          progression: 'double',
          notes: 'Single-leg strength and balance — base and top pressure.',
          substitutions: ['Walking Lunge', 'Step-Up'],
        },
        {
          id: 'hanging-leg-raise',
          name: 'Hanging Leg Raise',
          targetSets: 3,
          repRangeMin: 8,
          repRangeMax: 12,
          restSeconds: 60,
          loadIncrementKg: 0,
          progression: 'hold',
          notes: 'Hip flexors + core + a little grip. Strict, no swinging.',
          substitutions: ['Captain’s Chair Leg Raise'],
        },
        {
          id: 'copenhagen-plank',
          name: 'Copenhagen Plank',
          targetSets: 2,
          repRangeMin: 15,
          repRangeMax: 30,
          repUnit: 'seconds',
          perSide: true,
          restSeconds: 60,
          loadIncrementKg: 0,
          progression: 'none',
          notes: 'Adductors — guard strength and groin injury prevention.',
        },
      ],
    },
    {
      id: 'day-b-push',
      name: 'Day B — Upper Push + Physique',
      weekdayHints: [2], // Tuesday
      exercises: [
        {
          id: 'bench-press',
          name: 'Bench Press',
          targetSets: 4,
          repRangeMin: 5,
          repRangeMax: 7,
          targetRpe: 7,
          restSeconds: 180,
          loadIncrementKg: 2.5,
          progression: 'double',
          notes: 'Pressing power for frames and off-mat strength. Leave reps in the tank.',
          substitutions: ['DB Bench Press'],
        },
        {
          id: 'seated-db-press',
          name: 'Seated DB Shoulder Press',
          targetSets: 3,
          repRangeMin: 8,
          repRangeMax: 10,
          targetRpe: 8,
          restSeconds: 120,
          loadIncrementKg: 2,
          progression: 'double',
          notes: 'Shoulder strength and size.',
          substitutions: ['Machine Shoulder Press'],
        },
        {
          id: 'dips',
          name: 'Dips',
          targetSets: 2,
          repRangeMin: 8,
          repRangeMax: 12,
          targetRpe: 8,
          restSeconds: 90,
          loadIncrementKg: 2.5,
          progression: 'double',
          notes: 'Add weight once 12 bodyweight reps are easy.',
          substitutions: ['Close-Grip Bench Press'],
        },
        {
          id: 'lateral-raise',
          name: 'Lateral Raise',
          targetSets: 3,
          repRangeMin: 10,
          repRangeMax: 15,
          restSeconds: 60,
          loadIncrementKg: 1,
          progression: 'double',
          notes: 'Physique work — capped shoulders.',
          substitutions: ['Cable Lateral Raise'],
        },
        {
          id: 'triceps-pushdown',
          name: 'Cable Triceps Pushdown',
          targetSets: 3,
          repRangeMin: 10,
          repRangeMax: 15,
          restSeconds: 60,
          loadIncrementKg: 2.5,
          progression: 'double',
          substitutions: ['Overhead Cable Extension'],
        },
      ],
    },
    {
      id: 'day-c-pull',
      name: 'Day C — Upper Pull + Posterior',
      weekdayHints: [3], // Wednesday
      exercises: [
        {
          id: 'weighted-pullup',
          name: 'Weighted Pull-Up',
          targetSets: 4,
          repRangeMin: 5,
          repRangeMax: 7,
          targetRpe: 8,
          restSeconds: 180,
          loadIncrementKg: 2.5,
          progression: 'double',
          notes: 'The single best lift for BJJ — pulling strength and grip together.',
          substitutions: ['Lat Pulldown', 'Bodyweight Pull-Up'],
        },
        {
          id: 'chest-supported-row',
          name: 'Chest-Supported Row',
          targetSets: 3,
          repRangeMin: 8,
          repRangeMax: 10,
          targetRpe: 8,
          restSeconds: 120,
          loadIncrementKg: 2.5,
          progression: 'double',
          notes: 'Back thickness without loading the lower back before rolling.',
          substitutions: ['Seated Cable Row', 'DB Row'],
        },
        {
          id: 'face-pull',
          name: 'Face Pull',
          targetSets: 3,
          repRangeMin: 12,
          repRangeMax: 15,
          restSeconds: 60,
          loadIncrementKg: 2.5,
          progression: 'double',
          notes: 'Rear delts + rotator cuff — shoulder insurance for kimura grips.',
        },
        {
          id: 'back-extension',
          name: 'Back Extension',
          targetSets: 3,
          repRangeMin: 8,
          repRangeMax: 12,
          restSeconds: 90,
          loadIncrementKg: 2.5,
          progression: 'double',
          notes: 'Hold a plate once bodyweight is easy. Spinal erectors for posture in guard.',
        },
        {
          id: 'hammer-curl',
          name: 'Hammer Curl',
          targetSets: 3,
          repRangeMin: 8,
          repRangeMax: 12,
          restSeconds: 60,
          loadIncrementKg: 1,
          progression: 'double',
          notes: 'Brachialis + forearms — elbow protection against armbars, plus grip carryover.',
        },
      ],
    },
    {
      id: 'day-d-power',
      name: 'Day D — Power + Conditioning + Grip',
      weekdayHints: [5, 6], // Friday or Saturday
      exercises: [
        {
          id: 'trap-bar-deadlift',
          name: 'Trap Bar Deadlift',
          targetSets: 4,
          repRangeMin: 3,
          repRangeMax: 5,
          targetRpe: 7,
          restSeconds: 180,
          loadIncrementKg: 5,
          progression: 'double',
          notes: 'Explosive intent every rep — this is power work, not a grinder.',
          substitutions: ['Barbell Hip Thrust', 'Conventional Deadlift'],
        },
        {
          id: 'kb-swing',
          name: 'Kettlebell Swing',
          targetSets: 4,
          repRangeMin: 10,
          repRangeMax: 15,
          restSeconds: 90,
          loadIncrementKg: 4,
          progression: 'double',
          notes: 'Ballistic hip extension — the engine behind every takedown.',
        },
        {
          id: 'farmers-carry',
          name: 'Farmer’s Carry',
          targetSets: 3,
          repRangeMin: 30,
          repRangeMax: 40,
          repUnit: 'meters',
          restSeconds: 120,
          loadIncrementKg: 5,
          progression: 'double',
          notes: 'Grip day — furthest from the next BJJ session. Heavy as grip allows.',
          substitutions: ['Plate Pinch Carry', 'Dead Hang'],
        },
        {
          id: 'neck-work',
          name: 'Neck Curls / Extensions',
          targetSets: 2,
          repRangeMin: 12,
          repRangeMax: 15,
          restSeconds: 45,
          loadIncrementKg: 1.25,
          progression: 'hold',
          notes: 'Slow and controlled — neck strength is injury prevention for grappling.',
        },
        {
          id: 'bike-intervals',
          name: 'Assault Bike Intervals',
          targetSets: 6,
          repRangeMin: 20,
          repRangeMax: 20,
          repUnit: 'seconds',
          restSeconds: 40,
          loadIncrementKg: 0,
          progression: 'none',
          notes: '20s hard / 40s easy — alactic power for scrambles.',
          substitutions: ['Rower Sprints', 'Ski Erg'],
        },
      ],
    },
  ],
}
